EShoppingProject.Presentation/Areas/Admin/Controllers/CategoryController.cs
using EShoppingProject.Application.Models.DTOs.Category;
using EShoppingProject.Application.Services.Interfaces;
using EShoppingProject.Domain.Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EShoppingProject.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {

        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.CategoryList());
        }

        public async Task<IActionResult> PassiveToCategory()
        {
            return View(await _categoryService.GetToPassive());
        }

        public async Task<IActionResult> ActiveToCategory(int id)
        {
            var category = await _categoryService.GetActiveToCategory(id);
            return RedirectToAction("Index");

        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CategoryDTO model)
        {
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    await _categoryService.Create(model);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Update(int id) => View(await _categoryService.GetById(id));


        [HttpPost]
        public async Task<IActionResult> Update(CategoryDTO model)
        {
            if (ModelState.IsValid)
            {
                var category = await _categoryService.GetCategoryName(model);
                if (category != null)
                {
                    await _categoryService.Update(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "There is already a category..!");
                    TempData["Warning"] = "The page  is already exsist..!";
                    return View(category);
                }
            }
            else
            {
                TempData["Error"] = "The category hasn't been edited..!";
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var category = await _categoryService.GetById(id);
            if (category !=null)
            {
                await _categoryService.Delete(category);
                return RedirectToAction("Index");
            }
            return View("Index");
        }
    }
}

EShoppingProject.Presentation/Areas/Admin/Controllers/SubCategoryController.cs
using EShoppingProject.Application.Models.DTOs.SubCategory;
using EShoppingProject.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EShoppingProject.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubCategoryController : Controller
    {
        private readonly ISubCategoryService _subCategoryService;
        public SubCategoryController(ISubCategoryService subCategoryService)
        {
            _subCategoryService = subCategoryService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _subCategoryService.SubCategoryList());
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.CategoryId = new SelectList(await _subCategoryService.GetCategory(), "Id", "CategoryName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SubCategoryDTO model)
        {
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    await _subCategoryService.Create(model);
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "There is already a subcategory..!");
                TempData["Warning"] = "The sub  is already exsist..!";
                return View();
            }
            return View();

        }
        public async Task<IActionResult> Delete(int id)
        {
            var subcategoryId = await _subCategoryService.GetById(id);
            if (subcategoryId != null)
            {
                await _subCategoryService.Delete(subcategoryId);
                return RedirectToAction("Index");
            }
            return View("Index");
        }
    }
}

EShoppingProject.Presentation/Areas/Admin/Views/SubCategory/Create.cshtml
@model SubCategoryDTO
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row mt-2">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Create SubCategory</h4>
            </div>
            <div class="card-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group-sm">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group-sm">
                        <label asp-for="CategoryName" class="control-label"></label>
                        <select asp-for="CategoryId" asp-items="@ViewBag.CategoryId" class="form-control">
                            <option value="0">Choose Category</option>
                        </select>
                        <span asp-validation-for="CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group float-right m-2">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <a asp-action="Index" class="btn btn-block btn-dark">Back to List</a>
            </div>
        </div>
    </div>
</div>

EShoppingProject.Presentation/Areas/Admin/Views/SubCategory/Index.cshtml
@model IEnumerable<SubCategoryVMs>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row mt-2">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">List of SubCategories</div>
                @*<a asp-controller="Category" asp-action="PassiveToCategory" class="btn btn-primary ml-5">Show Passive Categories</a>*@

            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Category Name</th>
                            <th>Edit</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.CategoryName</td>

                                <td>
                                    <a asp-controller="SubCategory" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Update</a>
                                </td>
                                <td>
                                    <a asp-controller="SubCategory" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a asp-action="Create" class="btn btn-group-sm btn-primary">Create The New SubCategory</a>
            </div>

        </div>
    </div>
</div>