EShoppingProject.Presentation/Models/Components/CategoriesViewComponent.cs
using EShoppingProject.Application.Models.VMs;
using EShoppingProject.Application.Services.Interfaces;
using EShoppingProject.Domain.Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EShoppingProject.Presentation.Models.Components
{
    public class CategoriesViewComponent: ViewComponent
    {
        private readonly ICategoryService _categoryService;
       
        public CategoriesViewComponent(ICategoryService categoryService)
        {   
            _categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var list = await _categoryService.GetSubCategoryList();

            return View(list);
        }

    }
}

EShoppingProject.Presentation/Areas/Admin/Controllers/CategoryController.cs
using EShoppingProject.Application.Models.DTOs.Category;
using EShoppingProject.Application.Services.Interfaces;
using EShoppingProject.Domain.Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EShoppingProject.Presentation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {

        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.CategoryList());
        }

        public async Task<IActionResult> PassiveToCategory()
        {
            return View(await _categoryService.GetToPassive());
        }

        public async Task<IActionResult> ActiveToCategory(int id)
        {
            var category = await _categoryService.GetActiveToCategory(id);
            return RedirectToAction("Index");

        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CategoryDTO model)
        {
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    await _categoryService.Create(model);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Update(int id) => View(await _categoryService.GetById(id));


        [HttpPost]
        public async Task<IActionResult> Update(CategoryDTO model)
        {
            if (ModelState.IsValid)
            {
                var category = await _categoryService.GetCategoryName(model);
                if (category != null)
                {
                    await _categoryService.Update(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "There is already a category..!");
                    TempData["Warning"] = "The page  is already exsist..!";
                    return View(category);
                }
            }
            else
            {
                TempData["Error"] = "The category hasn't been edited..!";
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var category = await _categoryService.GetById(id);
            if (category !=null)
            {
                await _categoryService.Delete(category);
                return RedirectToAction("Index");
            }
            return View("Index");
        }
    }
}

EShoppingProject.Presentation/Views/Shared/_CategoriesListPartial.cshtml
@model IEnumerable<Category>


<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
     <div class="container">
         <div class="main-header">

             <ul class="list-group list-group-horizontal">
                 @foreach (var item in Model)
                 {
                     <li class="list-group-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">@item.CategoryName</a>
                     </li>
                 }
             </ul>
         </div>
     </div>
       
       
    </div>
</nav>

EShoppingProject.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Erdal BAKKAL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_NavBarPartial")

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-2">
                    @await Component.InvokeAsync("Categories")
                </div>
                <div class="col-8">
                    @RenderBody()
                </div>
                <div class="col-2">
                </div>
            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Erdal BAKKAL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EShoppingProject.Presentation/Views/Shared/_NavBarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Erdal BAKKAL</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--<div class="mx-auto">
            <form asp-controller="Search" asp-action="Index" method="get" id="searchform">
                <input class="form-control" type="search" name="userName" placeholder="Search" onkeypress="keypress(event)" aria-label="Search" />-->
        @*<button class="btn btn-outline-success" type="submit" onclick="keypress(event)">Search</button>*@
        <!--</form>
        </div>-->

        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @User.Identity.Name

            </button>
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <a class="btn" asp-controller="Account" asp-action="EditProfile" asp-route-username="@User.Identity.Name">Hesap Ayarları</a>
                    <a class="btn" asp-controller="Account" asp-action="Details" asp-route-username="@User.Identity.Name">Profili Görüntüle</a>
                    <a class="btn" asp-controller="" asp-action="" asp-route-username="">Yayında Olan Ürünlerim</a>
                </div>
            }

        </div>

        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <div class="navbar-nav ml-5">
                @if (User?.Identity?.IsAuthenticated ?? false)
                {
                    <div class="nav-item ml-1">
                        <form method="post" asp-controller="Account" asp-action="LogOut">
                            <button type="submit" class="btn btn-primary">Log Out</button>
                        </form>
                    </div>

                    @if (User.IsInRole("Admin")) //IsInRole("employee")
                    {
                        <div class="nav-item ml-1">
                            <form method="post" asp-area="Admin" asp-controller="Home" asp-action="Index">
                                <button type="submit" class="btn btn-primary">Admin Area</button>
                            </form>

                        </div>

                    }
                }
                else
                {
            <div class="nav-item ml-1">
                @*<a class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg" asp-area="" asp-controller="Account" asp-action="Login">Sign In</a>*@
                <a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="Login">Sign In</a>
            </div>
                    <div class="nav-item ml-1">
                        <a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a>
                    </div>

                    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="card">
                                                <div class="card-header">
                                                </div>
                                                @*@await Html.PartialAsync("Login/_LoginPartial")*@

                                                <div class="card-footer">
                                                    <a asp-controller="Account" asp-action="Register" class="btn btn-block btn-dark">Register</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</nav>